version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: product-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
